from typing import Protocol, Any

class BaseProgressBar(Protocol):
    progress_fraction: float
    animating: bool

    def set_fraction(self, fraction: float) -> None: ...
    def start_animation(self) -> None: ...
    def stop_animation(self) -> None: ...
    def get_widget(self) -> Any: ...
